### ISSUE TITLE
Is there a command to directly cull the cache?

### ISSUE THREAD

**Issue by Hoeze** [jnsnow/cachefilesd#1]
Hi, I'd need a command to make sure that there is at least `$n GB` of free disk space on the scratch partition.
Is there a way to directly control the cache size?

**Comment by jnsnow** [comment]
Whoa, hi! @Hoeze Sorry, I missed this comment. This is a very inactive fork, and I haven't worked on cachefilesd in five years.

I recommend you head to the linux-cachefs mailing list:
 https://www.redhat.com/mailman/listinfo/linux-cachefs

Sorry for the confusion!

**Comment by Hoeze** [comment]
Thanks for the recommendation @jnsnow :+1:
